--- mappng/ui/icons.lua
---
--- Loads the original 32x18 images from the user's ZIP. Their native TGX
--- encodings are generated by tools/build_icons.py. The button renderer draws
--- vanilla chrome first, then centres the corresponding image inside it.

local M = {}
local artwork = require("mappng.ui.artwork")

M.ICON_FILES = {
  import_heightmap = "ucp/modules/map-png/resources/icons/import_heightmap.png",
  export_heightmap = "ucp/modules/map-png/resources/icons/export_heightmap.png",
  import_textures = "ucp/modules/map-png/resources/icons/import_textures.png",
  export_textures = "ucp/modules/map-png/resources/icons/export_textures.png",
}

--- Short labels used by the text fallback.
M.LABELS = {
  import_heightmap = "H in",
  export_heightmap = "H out",
  import_textures = "T in",
  export_textures = "T out",
}

local state = { ready = false }

function M.available()
  return state.ready
end

--- Loads the native encodings of all four original PNGs.
---@return boolean ok
function M.load()
  artwork.load(M.ICON_FILES)
  state.ready = true
  return true
end

function M.unload()
  artwork.unload()
  state.ready = false
end

--- Draw only the picture; button chrome and interaction belong to the game.
function M.draw(key, rendering, x, y)
  assert(state.ready, "map-png: artwork is not loaded")
  artwork.draw(key, rendering, x, y)
end

return M
